package ddvudo.ORM.POJO;

import java.util.Date;

public class Ncov {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ncov.date
	 *
	 * @mbggenerated
	 */
	private Date date;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ncov.country
	 *
	 * @mbggenerated
	 */
	private String country;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ncov.countryCode
	 *
	 * @mbggenerated
	 */
	private String countrycode;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ncov.province
	 *
	 * @mbggenerated
	 */
	private String province;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ncov.provinceCode
	 *
	 * @mbggenerated
	 */
	private String provincecode;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ncov.city
	 *
	 * @mbggenerated
	 */
	private String city;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ncov.cityCode
	 *
	 * @mbggenerated
	 */
	private String citycode;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ncov.confirmed
	 *
	 * @mbggenerated
	 */
	private String confirmed;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ncov.suspected
	 *
	 * @mbggenerated
	 */
	private String suspected;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ncov.cured
	 *
	 * @mbggenerated
	 */
	private String cured;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ncov.dead
	 *
	 * @mbggenerated
	 */
	private String dead;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column ncov.date
	 *
	 * @return the value of ncov.date
	 * @mbggenerated
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column ncov.date
	 *
	 * @param date the value for ncov.date
	 * @mbggenerated
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column ncov.country
	 *
	 * @return the value of ncov.country
	 * @mbggenerated
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column ncov.country
	 *
	 * @param country the value for ncov.country
	 * @mbggenerated
	 */
	public void setCountry(String country) {
		this.country = country == null ? null : country.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column ncov.countryCode
	 *
	 * @return the value of ncov.countryCode
	 * @mbggenerated
	 */
	public String getCountrycode() {
		return countrycode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column ncov.countryCode
	 *
	 * @param countrycode the value for ncov.countryCode
	 * @mbggenerated
	 */
	public void setCountrycode(String countrycode) {
		this.countrycode = countrycode == null ? null : countrycode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column ncov.province
	 *
	 * @return the value of ncov.province
	 * @mbggenerated
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column ncov.province
	 *
	 * @param province the value for ncov.province
	 * @mbggenerated
	 */
	public void setProvince(String province) {
		this.province = province == null ? null : province.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column ncov.provinceCode
	 *
	 * @return the value of ncov.provinceCode
	 * @mbggenerated
	 */
	public String getProvincecode() {
		return provincecode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column ncov.provinceCode
	 *
	 * @param provincecode the value for ncov.provinceCode
	 * @mbggenerated
	 */
	public void setProvincecode(String provincecode) {
		this.provincecode = provincecode == null ? null : provincecode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column ncov.city
	 *
	 * @return the value of ncov.city
	 * @mbggenerated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column ncov.city
	 *
	 * @param city the value for ncov.city
	 * @mbggenerated
	 */
	public void setCity(String city) {
		this.city = city == null ? null : city.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column ncov.cityCode
	 *
	 * @return the value of ncov.cityCode
	 * @mbggenerated
	 */
	public String getCitycode() {
		return citycode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column ncov.cityCode
	 *
	 * @param citycode the value for ncov.cityCode
	 * @mbggenerated
	 */
	public void setCitycode(String citycode) {
		this.citycode = citycode == null ? null : citycode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column ncov.confirmed
	 *
	 * @return the value of ncov.confirmed
	 * @mbggenerated
	 */
	public String getConfirmed() {
		return confirmed;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column ncov.confirmed
	 *
	 * @param confirmed the value for ncov.confirmed
	 * @mbggenerated
	 */
	public void setConfirmed(String confirmed) {
		this.confirmed = confirmed == null ? null : confirmed.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column ncov.suspected
	 *
	 * @return the value of ncov.suspected
	 * @mbggenerated
	 */
	public String getSuspected() {
		return suspected;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column ncov.suspected
	 *
	 * @param suspected the value for ncov.suspected
	 * @mbggenerated
	 */
	public void setSuspected(String suspected) {
		this.suspected = suspected == null ? null : suspected.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column ncov.cured
	 *
	 * @return the value of ncov.cured
	 * @mbggenerated
	 */
	public String getCured() {
		return cured;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column ncov.cured
	 *
	 * @param cured the value for ncov.cured
	 * @mbggenerated
	 */
	public void setCured(String cured) {
		this.cured = cured == null ? null : cured.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column ncov.dead
	 *
	 * @return the value of ncov.dead
	 * @mbggenerated
	 */
	public String getDead() {
		return dead;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column ncov.dead
	 *
	 * @param dead the value for ncov.dead
	 * @mbggenerated
	 */
	public void setDead(String dead) {
		this.dead = dead == null ? null : dead.trim();
	}
}