package ORM.Mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface NcovMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov_data
	 *
	 * @mbggenerated
	 */
	int countByExample(NcovExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov_data
	 *
	 * @mbggenerated
	 */
	int deleteByExample(NcovExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov_data
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov_data
	 *
	 * @mbggenerated
	 */
	int insert(Ncov record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov_data
	 *
	 * @mbggenerated
	 */
	int insertSelective(Ncov record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov_data
	 *
	 * @mbggenerated
	 */
	List<Ncov> selectByExample(NcovExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov_data
	 *
	 * @mbggenerated
	 */
	Ncov selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov_data
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Ncov record, @Param("example") NcovExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov_data
	 *
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Ncov record, @Param("example") NcovExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov_data
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Ncov record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov_data
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Ncov record);
}