package ORM.Mapper;

import ORM.POJO.UploadFile;
import ORM.POJO.UploadFileExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface UploadFileMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table file
	 *
	 * @mbggenerated
	 */
	int countByExample(UploadFileExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table file
	 *
	 * @mbggenerated
	 */
	int deleteByExample(UploadFileExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table file
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table file
	 *
	 * @mbggenerated
	 */
	int insert(UploadFile record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table file
	 *
	 * @mbggenerated
	 */
	int insertSelective(UploadFile record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table file
	 *
	 * @mbggenerated
	 */
	List<UploadFile> selectByExample(UploadFileExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table file
	 *
	 * @mbggenerated
	 */
	UploadFile selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table file
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") UploadFile record, @Param("example") UploadFileExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table file
	 *
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") UploadFile record, @Param("example") UploadFileExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table file
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UploadFile record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table file
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UploadFile record);
}