package ddvudo.web.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class NcovExample {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table ncov
	 *
	 * @mbggenerated
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table ncov
	 *
	 * @mbggenerated
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table ncov
	 *
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov
	 *
	 * @mbggenerated
	 */
	public NcovExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov
	 *
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov
	 *
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov
	 *
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov
	 *
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov
	 *
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov
	 *
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov
	 *
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov
	 *
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov
	 *
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ncov
	 *
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table ncov
	 *
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andDateIsNull() {
			addCriterion("date is null");
			return (Criteria) this;
		}

		public Criteria andDateIsNotNull() {
			addCriterion("date is not null");
			return (Criteria) this;
		}

		public Criteria andDateEqualTo(Date value) {
			addCriterionForJDBCDate("date =", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("date <>", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateGreaterThan(Date value) {
			addCriterionForJDBCDate("date >", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("date >=", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateLessThan(Date value) {
			addCriterionForJDBCDate("date <", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("date <=", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateIn(List<Date> values) {
			addCriterionForJDBCDate("date in", values, "date");
			return (Criteria) this;
		}

		public Criteria andDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("date not in", values, "date");
			return (Criteria) this;
		}

		public Criteria andDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("date between", value1, value2, "date");
			return (Criteria) this;
		}

		public Criteria andDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("date not between", value1, value2, "date");
			return (Criteria) this;
		}

		public Criteria andCountryIsNull() {
			addCriterion("country is null");
			return (Criteria) this;
		}

		public Criteria andCountryIsNotNull() {
			addCriterion("country is not null");
			return (Criteria) this;
		}

		public Criteria andCountryEqualTo(String value) {
			addCriterion("country =", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotEqualTo(String value) {
			addCriterion("country <>", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryGreaterThan(String value) {
			addCriterion("country >", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryGreaterThanOrEqualTo(String value) {
			addCriterion("country >=", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryLessThan(String value) {
			addCriterion("country <", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryLessThanOrEqualTo(String value) {
			addCriterion("country <=", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryLike(String value) {
			addCriterion("country like", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotLike(String value) {
			addCriterion("country not like", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryIn(List<String> values) {
			addCriterion("country in", values, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotIn(List<String> values) {
			addCriterion("country not in", values, "country");
			return (Criteria) this;
		}

		public Criteria andCountryBetween(String value1, String value2) {
			addCriterion("country between", value1, value2, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotBetween(String value1, String value2) {
			addCriterion("country not between", value1, value2, "country");
			return (Criteria) this;
		}

		public Criteria andCountrycodeIsNull() {
			addCriterion("countryCode is null");
			return (Criteria) this;
		}

		public Criteria andCountrycodeIsNotNull() {
			addCriterion("countryCode is not null");
			return (Criteria) this;
		}

		public Criteria andCountrycodeEqualTo(String value) {
			addCriterion("countryCode =", value, "countrycode");
			return (Criteria) this;
		}

		public Criteria andCountrycodeNotEqualTo(String value) {
			addCriterion("countryCode <>", value, "countrycode");
			return (Criteria) this;
		}

		public Criteria andCountrycodeGreaterThan(String value) {
			addCriterion("countryCode >", value, "countrycode");
			return (Criteria) this;
		}

		public Criteria andCountrycodeGreaterThanOrEqualTo(String value) {
			addCriterion("countryCode >=", value, "countrycode");
			return (Criteria) this;
		}

		public Criteria andCountrycodeLessThan(String value) {
			addCriterion("countryCode <", value, "countrycode");
			return (Criteria) this;
		}

		public Criteria andCountrycodeLessThanOrEqualTo(String value) {
			addCriterion("countryCode <=", value, "countrycode");
			return (Criteria) this;
		}

		public Criteria andCountrycodeLike(String value) {
			addCriterion("countryCode like", value, "countrycode");
			return (Criteria) this;
		}

		public Criteria andCountrycodeNotLike(String value) {
			addCriterion("countryCode not like", value, "countrycode");
			return (Criteria) this;
		}

		public Criteria andCountrycodeIn(List<String> values) {
			addCriterion("countryCode in", values, "countrycode");
			return (Criteria) this;
		}

		public Criteria andCountrycodeNotIn(List<String> values) {
			addCriterion("countryCode not in", values, "countrycode");
			return (Criteria) this;
		}

		public Criteria andCountrycodeBetween(String value1, String value2) {
			addCriterion("countryCode between", value1, value2, "countrycode");
			return (Criteria) this;
		}

		public Criteria andCountrycodeNotBetween(String value1, String value2) {
			addCriterion("countryCode not between", value1, value2, "countrycode");
			return (Criteria) this;
		}

		public Criteria andProvinceIsNull() {
			addCriterion("province is null");
			return (Criteria) this;
		}

		public Criteria andProvinceIsNotNull() {
			addCriterion("province is not null");
			return (Criteria) this;
		}

		public Criteria andProvinceEqualTo(String value) {
			addCriterion("province =", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotEqualTo(String value) {
			addCriterion("province <>", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceGreaterThan(String value) {
			addCriterion("province >", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceGreaterThanOrEqualTo(String value) {
			addCriterion("province >=", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceLessThan(String value) {
			addCriterion("province <", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceLessThanOrEqualTo(String value) {
			addCriterion("province <=", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceLike(String value) {
			addCriterion("province like", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotLike(String value) {
			addCriterion("province not like", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceIn(List<String> values) {
			addCriterion("province in", values, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotIn(List<String> values) {
			addCriterion("province not in", values, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceBetween(String value1, String value2) {
			addCriterion("province between", value1, value2, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotBetween(String value1, String value2) {
			addCriterion("province not between", value1, value2, "province");
			return (Criteria) this;
		}

		public Criteria andProvincecodeIsNull() {
			addCriterion("provinceCode is null");
			return (Criteria) this;
		}

		public Criteria andProvincecodeIsNotNull() {
			addCriterion("provinceCode is not null");
			return (Criteria) this;
		}

		public Criteria andProvincecodeEqualTo(String value) {
			addCriterion("provinceCode =", value, "provincecode");
			return (Criteria) this;
		}

		public Criteria andProvincecodeNotEqualTo(String value) {
			addCriterion("provinceCode <>", value, "provincecode");
			return (Criteria) this;
		}

		public Criteria andProvincecodeGreaterThan(String value) {
			addCriterion("provinceCode >", value, "provincecode");
			return (Criteria) this;
		}

		public Criteria andProvincecodeGreaterThanOrEqualTo(String value) {
			addCriterion("provinceCode >=", value, "provincecode");
			return (Criteria) this;
		}

		public Criteria andProvincecodeLessThan(String value) {
			addCriterion("provinceCode <", value, "provincecode");
			return (Criteria) this;
		}

		public Criteria andProvincecodeLessThanOrEqualTo(String value) {
			addCriterion("provinceCode <=", value, "provincecode");
			return (Criteria) this;
		}

		public Criteria andProvincecodeLike(String value) {
			addCriterion("provinceCode like", value, "provincecode");
			return (Criteria) this;
		}

		public Criteria andProvincecodeNotLike(String value) {
			addCriterion("provinceCode not like", value, "provincecode");
			return (Criteria) this;
		}

		public Criteria andProvincecodeIn(List<String> values) {
			addCriterion("provinceCode in", values, "provincecode");
			return (Criteria) this;
		}

		public Criteria andProvincecodeNotIn(List<String> values) {
			addCriterion("provinceCode not in", values, "provincecode");
			return (Criteria) this;
		}

		public Criteria andProvincecodeBetween(String value1, String value2) {
			addCriterion("provinceCode between", value1, value2, "provincecode");
			return (Criteria) this;
		}

		public Criteria andProvincecodeNotBetween(String value1, String value2) {
			addCriterion("provinceCode not between", value1, value2, "provincecode");
			return (Criteria) this;
		}

		public Criteria andCityIsNull() {
			addCriterion("city is null");
			return (Criteria) this;
		}

		public Criteria andCityIsNotNull() {
			addCriterion("city is not null");
			return (Criteria) this;
		}

		public Criteria andCityEqualTo(String value) {
			addCriterion("city =", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotEqualTo(String value) {
			addCriterion("city <>", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThan(String value) {
			addCriterion("city >", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThanOrEqualTo(String value) {
			addCriterion("city >=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThan(String value) {
			addCriterion("city <", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThanOrEqualTo(String value) {
			addCriterion("city <=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLike(String value) {
			addCriterion("city like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotLike(String value) {
			addCriterion("city not like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityIn(List<String> values) {
			addCriterion("city in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotIn(List<String> values) {
			addCriterion("city not in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityBetween(String value1, String value2) {
			addCriterion("city between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotBetween(String value1, String value2) {
			addCriterion("city not between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andCitycodeIsNull() {
			addCriterion("cityCode is null");
			return (Criteria) this;
		}

		public Criteria andCitycodeIsNotNull() {
			addCriterion("cityCode is not null");
			return (Criteria) this;
		}

		public Criteria andCitycodeEqualTo(String value) {
			addCriterion("cityCode =", value, "citycode");
			return (Criteria) this;
		}

		public Criteria andCitycodeNotEqualTo(String value) {
			addCriterion("cityCode <>", value, "citycode");
			return (Criteria) this;
		}

		public Criteria andCitycodeGreaterThan(String value) {
			addCriterion("cityCode >", value, "citycode");
			return (Criteria) this;
		}

		public Criteria andCitycodeGreaterThanOrEqualTo(String value) {
			addCriterion("cityCode >=", value, "citycode");
			return (Criteria) this;
		}

		public Criteria andCitycodeLessThan(String value) {
			addCriterion("cityCode <", value, "citycode");
			return (Criteria) this;
		}

		public Criteria andCitycodeLessThanOrEqualTo(String value) {
			addCriterion("cityCode <=", value, "citycode");
			return (Criteria) this;
		}

		public Criteria andCitycodeLike(String value) {
			addCriterion("cityCode like", value, "citycode");
			return (Criteria) this;
		}

		public Criteria andCitycodeNotLike(String value) {
			addCriterion("cityCode not like", value, "citycode");
			return (Criteria) this;
		}

		public Criteria andCitycodeIn(List<String> values) {
			addCriterion("cityCode in", values, "citycode");
			return (Criteria) this;
		}

		public Criteria andCitycodeNotIn(List<String> values) {
			addCriterion("cityCode not in", values, "citycode");
			return (Criteria) this;
		}

		public Criteria andCitycodeBetween(String value1, String value2) {
			addCriterion("cityCode between", value1, value2, "citycode");
			return (Criteria) this;
		}

		public Criteria andCitycodeNotBetween(String value1, String value2) {
			addCriterion("cityCode not between", value1, value2, "citycode");
			return (Criteria) this;
		}

		public Criteria andConfirmedIsNull() {
			addCriterion("confirmed is null");
			return (Criteria) this;
		}

		public Criteria andConfirmedIsNotNull() {
			addCriterion("confirmed is not null");
			return (Criteria) this;
		}

		public Criteria andConfirmedEqualTo(String value) {
			addCriterion("confirmed =", value, "confirmed");
			return (Criteria) this;
		}

		public Criteria andConfirmedNotEqualTo(String value) {
			addCriterion("confirmed <>", value, "confirmed");
			return (Criteria) this;
		}

		public Criteria andConfirmedGreaterThan(String value) {
			addCriterion("confirmed >", value, "confirmed");
			return (Criteria) this;
		}

		public Criteria andConfirmedGreaterThanOrEqualTo(String value) {
			addCriterion("confirmed >=", value, "confirmed");
			return (Criteria) this;
		}

		public Criteria andConfirmedLessThan(String value) {
			addCriterion("confirmed <", value, "confirmed");
			return (Criteria) this;
		}

		public Criteria andConfirmedLessThanOrEqualTo(String value) {
			addCriterion("confirmed <=", value, "confirmed");
			return (Criteria) this;
		}

		public Criteria andConfirmedLike(String value) {
			addCriterion("confirmed like", value, "confirmed");
			return (Criteria) this;
		}

		public Criteria andConfirmedNotLike(String value) {
			addCriterion("confirmed not like", value, "confirmed");
			return (Criteria) this;
		}

		public Criteria andConfirmedIn(List<String> values) {
			addCriterion("confirmed in", values, "confirmed");
			return (Criteria) this;
		}

		public Criteria andConfirmedNotIn(List<String> values) {
			addCriterion("confirmed not in", values, "confirmed");
			return (Criteria) this;
		}

		public Criteria andConfirmedBetween(String value1, String value2) {
			addCriterion("confirmed between", value1, value2, "confirmed");
			return (Criteria) this;
		}

		public Criteria andConfirmedNotBetween(String value1, String value2) {
			addCriterion("confirmed not between", value1, value2, "confirmed");
			return (Criteria) this;
		}

		public Criteria andSuspectedIsNull() {
			addCriterion("suspected is null");
			return (Criteria) this;
		}

		public Criteria andSuspectedIsNotNull() {
			addCriterion("suspected is not null");
			return (Criteria) this;
		}

		public Criteria andSuspectedEqualTo(String value) {
			addCriterion("suspected =", value, "suspected");
			return (Criteria) this;
		}

		public Criteria andSuspectedNotEqualTo(String value) {
			addCriterion("suspected <>", value, "suspected");
			return (Criteria) this;
		}

		public Criteria andSuspectedGreaterThan(String value) {
			addCriterion("suspected >", value, "suspected");
			return (Criteria) this;
		}

		public Criteria andSuspectedGreaterThanOrEqualTo(String value) {
			addCriterion("suspected >=", value, "suspected");
			return (Criteria) this;
		}

		public Criteria andSuspectedLessThan(String value) {
			addCriterion("suspected <", value, "suspected");
			return (Criteria) this;
		}

		public Criteria andSuspectedLessThanOrEqualTo(String value) {
			addCriterion("suspected <=", value, "suspected");
			return (Criteria) this;
		}

		public Criteria andSuspectedLike(String value) {
			addCriterion("suspected like", value, "suspected");
			return (Criteria) this;
		}

		public Criteria andSuspectedNotLike(String value) {
			addCriterion("suspected not like", value, "suspected");
			return (Criteria) this;
		}

		public Criteria andSuspectedIn(List<String> values) {
			addCriterion("suspected in", values, "suspected");
			return (Criteria) this;
		}

		public Criteria andSuspectedNotIn(List<String> values) {
			addCriterion("suspected not in", values, "suspected");
			return (Criteria) this;
		}

		public Criteria andSuspectedBetween(String value1, String value2) {
			addCriterion("suspected between", value1, value2, "suspected");
			return (Criteria) this;
		}

		public Criteria andSuspectedNotBetween(String value1, String value2) {
			addCriterion("suspected not between", value1, value2, "suspected");
			return (Criteria) this;
		}

		public Criteria andCuredIsNull() {
			addCriterion("cured is null");
			return (Criteria) this;
		}

		public Criteria andCuredIsNotNull() {
			addCriterion("cured is not null");
			return (Criteria) this;
		}

		public Criteria andCuredEqualTo(String value) {
			addCriterion("cured =", value, "cured");
			return (Criteria) this;
		}

		public Criteria andCuredNotEqualTo(String value) {
			addCriterion("cured <>", value, "cured");
			return (Criteria) this;
		}

		public Criteria andCuredGreaterThan(String value) {
			addCriterion("cured >", value, "cured");
			return (Criteria) this;
		}

		public Criteria andCuredGreaterThanOrEqualTo(String value) {
			addCriterion("cured >=", value, "cured");
			return (Criteria) this;
		}

		public Criteria andCuredLessThan(String value) {
			addCriterion("cured <", value, "cured");
			return (Criteria) this;
		}

		public Criteria andCuredLessThanOrEqualTo(String value) {
			addCriterion("cured <=", value, "cured");
			return (Criteria) this;
		}

		public Criteria andCuredLike(String value) {
			addCriterion("cured like", value, "cured");
			return (Criteria) this;
		}

		public Criteria andCuredNotLike(String value) {
			addCriterion("cured not like", value, "cured");
			return (Criteria) this;
		}

		public Criteria andCuredIn(List<String> values) {
			addCriterion("cured in", values, "cured");
			return (Criteria) this;
		}

		public Criteria andCuredNotIn(List<String> values) {
			addCriterion("cured not in", values, "cured");
			return (Criteria) this;
		}

		public Criteria andCuredBetween(String value1, String value2) {
			addCriterion("cured between", value1, value2, "cured");
			return (Criteria) this;
		}

		public Criteria andCuredNotBetween(String value1, String value2) {
			addCriterion("cured not between", value1, value2, "cured");
			return (Criteria) this;
		}

		public Criteria andDeadIsNull() {
			addCriterion("dead is null");
			return (Criteria) this;
		}

		public Criteria andDeadIsNotNull() {
			addCriterion("dead is not null");
			return (Criteria) this;
		}

		public Criteria andDeadEqualTo(String value) {
			addCriterion("dead =", value, "dead");
			return (Criteria) this;
		}

		public Criteria andDeadNotEqualTo(String value) {
			addCriterion("dead <>", value, "dead");
			return (Criteria) this;
		}

		public Criteria andDeadGreaterThan(String value) {
			addCriterion("dead >", value, "dead");
			return (Criteria) this;
		}

		public Criteria andDeadGreaterThanOrEqualTo(String value) {
			addCriterion("dead >=", value, "dead");
			return (Criteria) this;
		}

		public Criteria andDeadLessThan(String value) {
			addCriterion("dead <", value, "dead");
			return (Criteria) this;
		}

		public Criteria andDeadLessThanOrEqualTo(String value) {
			addCriterion("dead <=", value, "dead");
			return (Criteria) this;
		}

		public Criteria andDeadLike(String value) {
			addCriterion("dead like", value, "dead");
			return (Criteria) this;
		}

		public Criteria andDeadNotLike(String value) {
			addCriterion("dead not like", value, "dead");
			return (Criteria) this;
		}

		public Criteria andDeadIn(List<String> values) {
			addCriterion("dead in", values, "dead");
			return (Criteria) this;
		}

		public Criteria andDeadNotIn(List<String> values) {
			addCriterion("dead not in", values, "dead");
			return (Criteria) this;
		}

		public Criteria andDeadBetween(String value1, String value2) {
			addCriterion("dead between", value1, value2, "dead");
			return (Criteria) this;
		}

		public Criteria andDeadNotBetween(String value1, String value2) {
			addCriterion("dead not between", value1, value2, "dead");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table ncov
	 *
	 * @mbggenerated do_not_delete_during_merge
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table ncov
	 *
	 * @mbggenerated
	 */
	public static class Criterion {
		private final String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private final String typeHandler;

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}
	}
}
