package ddvudo.web.bean;

import java.util.Date;

public class UploadFile {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column file.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column file.filename
	 *
	 * @mbggenerated
	 */
	private String filename;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column file.createtime
	 *
	 * @mbggenerated
	 */
	private Date createtime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column file.owner
	 *
	 * @mbggenerated
	 */
	private String owner;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column file.ownerid
	 *
	 * @mbggenerated
	 */
	private Integer ownerid;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column file.realname
	 *
	 * @mbggenerated
	 */
	private String realname;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column file.id
	 *
	 * @return the value of file.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column file.id
	 *
	 * @param id the value for file.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column file.filename
	 *
	 * @return the value of file.filename
	 * @mbggenerated
	 */
	public String getFilename() {
		return filename;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column file.filename
	 *
	 * @param filename the value for file.filename
	 * @mbggenerated
	 */
	public void setFilename(String filename) {
		this.filename = filename == null ? null : filename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column file.createtime
	 *
	 * @return the value of file.createtime
	 * @mbggenerated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column file.createtime
	 *
	 * @param createtime the value for file.createtime
	 * @mbggenerated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column file.owner
	 *
	 * @return the value of file.owner
	 * @mbggenerated
	 */
	public String getOwner() {
		return owner;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column file.owner
	 *
	 * @param owner the value for file.owner
	 * @mbggenerated
	 */
	public void setOwner(String owner) {
		this.owner = owner == null ? null : owner.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column file.ownerid
	 *
	 * @return the value of file.ownerid
	 * @mbggenerated
	 */
	public Integer getOwnerid() {
		return ownerid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column file.ownerid
	 *
	 * @param ownerid the value for file.ownerid
	 * @mbggenerated
	 */
	public void setOwnerid(Integer ownerid) {
		this.ownerid = ownerid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column file.realname
	 *
	 * @return the value of file.realname
	 * @mbggenerated
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column file.realname
	 *
	 * @param realname the value for file.realname
	 * @mbggenerated
	 */
	public void setRealname(String realname) {
		this.realname = realname == null ? null : realname.trim();
	}
}
